name: ci-demo

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: zhixiuyue/parser_vue3
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install dependencies
      run: pnpm i
    - name: Build project
      run: npm run build
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./demo_for_use
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo_for_use
